<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "add".
 *
 * @property int $id
 * @property string|null $adress
 * @property int|null $owner_id
 * @property int|null $type_id
 * @property string|null $photo

 *
 * @property User $owner
 * @property Type $type
 * @property Deal[] $deals
 */
class Add extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'add';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['owner_id', 'type_id'], 'integer'],
            [['adress'], 'string', 'max' => 255],
            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['owner_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => Type::className(), 'targetAttribute' => ['type_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'adress' => 'Адреса',
            'owner_id' => 'ID власника',
            'type_id' => 'Тип площини',
            'photo' => 'Фото',
        ];
    }

    public function setOrder($i)
    {
        $this->is_ordered = $i;
        return $this->save(false);
    }
    public function saveType($type_id)
    {
        $type = Type::findOne($type_id);
        if($type != null)
        {
            $this->link('type', $type);
            return true;
        }
    }
    public function saveOwner($owner_id)
    {
        $owner = User::findOne($owner_id);
        if($owner != null)
        {
            $this->link('owner', $owner);
            return true;
        }
    }

    public function saveImage($filename)
    {
        $this->photo = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->photo) ? '/uploads/' . $this->photo : '/no-image.jpg';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->photo);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[Owner]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(User::className(), ['id' => 'owner_id']);
    }

    /**
     * Gets query for [[Type]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(Type::className(), ['id' => 'type_id']);
    }

    /**
     * Gets query for [[Deals]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDeals()
    {
        return $this->hasMany(Deal::className(), ['add_id' => 'id']);
    }
}
